### ISSUE TITLE
[bug] Close Headunit

### ISSUE THREAD

**Issue by viktorgino** [viktorgino/headunit-desktop#12]
As reported by @szeater:

'If you hit the gauge icon in AA, where the 'Return to Mazda Connect' option is, AA just hangs'

Test what this should actually do and change the label to 'Return to Headunit Desktop'

**Comment by nermolov** [comment]
In my actual AA Headunit in my Volkswagen it returns to the stock interface. Seeing as there is a way to jump out of the interface on the right side in headunit-desktop, I think it would be best to disable this entirely.

**Comment by viktorgino** [comment]
I agree, it'd be good to not even have the button there. I'll look into how to remove it.
