### ISSUE TITLE
Support for official Raspberry Pi Touch Display

### ISSUE THREAD

**Issue by suhrmann** [viktorgino/headunit-desktop#14]
I connected the _7" Raspberry Pi Touch Display_ and am using the latest headuni image (``image_2017-08-17-Raspbian-viktorginos-headunit-lite.zip``) as is with the changes from [Setting up the PI](http://headunit.viktorgino.me/RPI-INSTRUCTIONS): Setup the WiFi, Rotate the screen, Increase the GPU memory and Enable SSH.

After ``apt-get update && apt-get upgrade`` I started the headunit successfuly!

### xinit
But the touchscreen-input doesn't work properly. It rarely recognizes touch-input - but if it does, the input is correct.
I assume the error is linked to the log entries 
```
InputFactory: Input device: "auto"
InputFactory: No valid device found use Null device instead.
```
Full log on [pastebin](https://pastebin.com/kVzxLRs4).

### OpenGL
Trying to launch it with OpenGL gives the error
```
QXcbConnection: Could not connect to display
```
Full log on [pastebin](https://pastebin.com/pFykdiBg).

**Comment by suhrmann** [comment]
I found the reason and the solution for the input-problems with **xinit**
After removing ``lcd_rotate=2`` from the config the headunit works 🎉

**Comment by viktorgino** [comment]
if you run it with `QT_QPA_PLATFORM=eglfs /opt/headunit-desktop/headunit-app` it runs with the VC4 driver

**Comment by viktorgino** [comment]
you can make it permanent by changing it in `/etc/environment`

**Comment by viktorgino** [comment]
```
InputFactory: Input device: "auto"
InputFactory: No valid device found use Null device instead.
```
is from welle.io :). I'll look into trying to tag debug messages, it does get confusing sometimes

**Comment by suhrmann** [comment]
Even with using the VC4 drivers, the display stays black. And the screen ration is wrong (except it's the hu-content ratio). If I don't add ``sudo`` the screen stays black as well and the device (AA) isn't recognized.
[Log](https://pastebin.com/zXzTdvxS)
