### ISSUE TITLE
Compatible screen

### ISSUE THREAD

**Issue by MrNHQ** [viktorgino/headunit-desktop#16]
Hello,

I would like to try to put your project in my car.
I dowloaded your image and tested it on my TV and an old VGA screen, both were working fine.

Then I tried on a 3,5 inch TFT screen (connected with gpio pins).
using the `xinit` I got an error
`Fatal server error:
(EE) no screen found(EE)`
and using 
`QT_QPA_PLATFORM=eglfs
/opt/headunit-desktop/headunit-app`
I got:
`QXcbConnection: Could not connect to display`
I also read the question about the official 7' inch screen not yet compatible.
Would you know how I can use these screens? or which screens can I use?

**Comment by viktorgino** [comment]
@MrNHQ Should be working with most displays, I'll double check it on my Pi setup in the next couple of days to make sure everything is as it should be.

**Comment by viktorgino** [comment]
To get it working with the Pi screen you need to edit `/boot/config.txt` and change `dtoverlay=vc4-kms-v3d` to `dtoverlay=vc4-fkms-v3d` and add `lcd_rotate=2`

Headunit should work with `QT_QPA_PLATFORM=eglfs /opt/headunit-desktop/headunit-app` only without xinit or sudo.

**Comment by joshsoucie** [comment]
Getting this setup now similarly with a 3.5in backpack lcd

Hardware:
Raspi 3b
3.5in lcd from [waveshare](https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(A))

Using xinit, I got the same error:

`Fatal server error: (EE) no screen found(EE)`

And on running `QT_QPA_PLATFORM=eglfs [loc of headunit-app]`, received the error:

`Could not find DRM device!`

Thoughts?

Looks like [this guy rebuilt everything](https://forum.qt.io/topic/82025/cannot-find-drm-device-qt5-9-0-with-eglfs/4) but I'd rather not...-___-
