### ISSUE TITLE
Error getting manufacturer string from device

### ISSUE THREAD

**Issue by limones1319** [viktorgino/headunit-desktop#17]
Hello,

I was trying today to build your project. I managed to start the headunit-app, but  I am receving these errors when I plug the phone to the Raspberry pi via USB:

Device attached:   10007:65344 (bus 1, device 7 path: 1.2) | Serial no.:  | bDeviceClass:0
remove 
Error getting manufacturer string from device: 0x2717:0xff40 | Manufacturer string set as Unknown
Error getting product string from device: 0x2717:0xff40 | Product string set as Unknown
Error getting serial number from device: 0x2717:0xff40 | Serial number string set as Unknown

The phone is a Xiaomi Redmi 4. If I start Android Auto, I can not see anything on the Rpi screen. 

Thank you.
Gabriel

**Comment by viktorgino** [comment]
Hi

The USB connection listener is currently not working, that's why you get this error. I'm working on a fix, but to get AA started you have to start it manually by going into Settings-> Android Auto and click restart in the bottom left corner.

**Comment by viktorgino** [comment]
Fixed with https://github.com/viktorgino/headunit-desktop/tree/master/modules/usbconnectionlistener
