### ISSUE TITLE
Android Auto in fullscreen

### ISSUE THREAD

**Issue by latroupadd** [viktorgino/headunit-desktop#18]
Hello I discovered your project yesterday and I installed it today: everything works like a charm !

I just wanted to know if it was possible to change the interface to have Android Auto in fullscreen (I want to delete the features on the right side).

Can you tell me which files I have to modify to do this ?

**Comment by viktorgino** [comment]
Hi

The easiest way to do this would be by creating a new qml file with a `Window` and import [aaVideo.qml](https://github.com/viktorgino/headunit-desktop/blob/master/aaVideo.qml) file, then load the new qml file in [main.cpp](https://github.com/viktorgino/headunit-desktop/blob/master/main.cpp). Have a look at [qml_gui/qml/main.qml](https://github.com/viktorgino/headunit-gui/blob/dbcc63749acf2d631fee993007bb3fc4f926526d/qml/main.qml). If you want to do this then I'd recommend getting rid of all the now unneded dependencies in main.cpp and [app.pro](https://github.com/viktorgino/headunit-desktop/blob/master/app.pro) files.

**Comment by latroupadd** [comment]
Okay, thanks for your reply. I'll do next week.
