### ISSUE TITLE
Android Auto Mic doesnt work

### ISSUE THREAD

**Issue by nermolov** [viktorgino/headunit-desktop#19]
Mic is enabled in both alsa and pulse. Starting a microphone listen session on android auto renders the following log output while not having any output:

```
SHAI1 : Mic Started

** (headunit-app:4548): CRITICAL **: gst_app_sink_try_pull_sample: assertion 'GST_IS_APP_SINK (appsink)' failed

(headunit-app:4548): GStreamer-CRITICAL **: gst_sample_get_buffer: assertion 'GST_IS_SAMPLE (sample)' failed
```

**Comment by viktorgino** [comment]
Hi

I've come across this issue before, will have a look again, because it is fairly annoying.

**Comment by DavMon** [comment]
Do I need to do something to enable the usb microphone or should it just be plug and play? I have one but it doesn't send any input to the pi
