### ISSUE TITLE
Unable to build commit 5abc0cf  

### ISSUE THREAD

**Issue by mrsylerpowers** [viktorgino/headunit-desktop#23]
I keep on getting the error on multiple systems Project `ERROR: qofono-qt5 development package not found`

**Comment by viktorgino** [comment]
What system are you trying to build it on?

**Comment by mrsylerpowers** [comment]
Ubuntu 17.10. I reverted my master build to the commit before this one and worked just fine.

**Comment by WarDrake** [comment]
The rpi3 using Stretch throws the exact same error.

**Comment by viktorgino** [comment]
Hi

This should be sorted by now, it was an issue with a git reset.
