### ISSUE TITLE
[Feature Request] OEM HW Support

### ISSUE THREAD

**Issue by shawngmc** [viktorgino/headunit-desktop#25]
Is there any intent to support arbitrary OEM buttons via GPIO or backup/dash cameras?

**Comment by viktorgino** [comment]
Hi

Yes there is, and I'm slowly working towards it, but it takes some planning. The plan is that I do a config system where support for cars can be added using a config file. Additionally I'll add a d-bus interface so you can control the app from a daemon etc.

**Comment by viktorgino** [comment]
What car do you have and have you looked at how the oem buttons communicate with the factory headunit? (ie through can bus or something more simpler).
