### ISSUE TITLE
Buildroot support - request for fast boot rpi

### ISSUE THREAD

**Issue by gregd72002** [viktorgino/headunit-desktop#35]
The idea is to have a RPi image. Use buildtool to build all the dependencies including headunit-desktop for RPi and to support fast boot time. 

Call it something like headunit-desktop-rpi-imagebuilder

**Comment by viktorgino** [comment]
There is https://github.com/viktorgino/pi-gen which is based on the official Pi foundation image build tool. The building of packages was part of this repo, but to save time I've setup my own debian repository on http://apt.viktorgino.me/. The build scripts for this repo aren't public at the moment, but I want to publish it and set it up so it automatically builds and uploads it to the deb repo.

The built Rpi images can be found here: http://files.headunit.viktorgino.me/index.html

**Comment by viktorgino** [comment]
As mentioned in my email I like the approach of https://github.com/gregd72002/headunit-desktop-rpi-imagebuilder and planning to use it and maybe combine it with pi-gen. I've created a project for it so we can keep track of any progress on this
