### ISSUE TITLE
Change brightness

### ISSUE THREAD

**Issue by Rootinator** [viktorgino/headunit-desktop#36]
Hello,

how can I change the brightness without SSH?

**Comment by viktorgino** [comment]
There isn't really a way yet. What screen are you using?

**Comment by Rootinator** [comment]
I use the official touchscreen for Raspberry Pi

**Comment by gregd72002** [comment]
@Rootinator , we are working to have it implemented in the next release. Meantime it is already working in this fork: https://github.com/gregd72002/headunit-desktop

**Comment by Rootinator** [comment]
How can I add the new feature to an existing system without having to reinstall the whole system?

**Comment by gregd72002** [comment]
The brightness plugin requires some extra functionality that was not present in previous version on headunit-desktop. As such update to headunit-desktop is needed.
@viktorgino  might have more information on the build process

**Comment by viktorgino** [comment]
@gregd72002 it is built by pi-ge, headunit is built here : https://github.com/viktorgino/pi-gen/blob/master/stage4/01-install-headunit/00-run.sh

**Comment by Rootinator** [comment]
How should I proceed?

I open an SSH session and call the file or do I need to install a fresh Debian and create the file?

**Comment by viktorgino** [comment]
@Rootinator no need to reinstall, if you cd to `/opt/headunit-desktop` then pull the latest from the git remote : `git pull --recurse-submodules` and run `qmake CONFIG+=rpi -config release` then `make -j2` this should rebuild it, then restart the pi and you should have the latest headunit installed

**Comment by Rootinator** [comment]
When I execute these commands and then restart the Raspberry (sudo reboot now), the headunit window will not boot.

He shows the picture with the speedometer with "Viktorgino's Headunit Desktop". After that comes nothing after many minutes.

**Comment by viktorgino** [comment]
@Rootinator what's the output of `journalctl -u headunit -b`?

**Comment by Rootinator** [comment]
This is the result of "journalctl -u headunit -b":

```
-- Logs begin at Thu 2016-11-03 18:16:42 CET, end at Wed 2019-06-05 21:03:33 CEST. --
Jun 05 21:02:40 raspberrypi systemd[1]: Started Viktorgino's Headunit Desktop Service.
Jun 05 21:02:41 raspberrypi headunit-app[440]: MESA-LOADER: failed to retrieve device information
Jun 05 21:02:42 raspberrypi headunit-app[440]: MESA-LOADER: failed to retrieve device information
Jun 05 21:02:42 raspberrypi headunit-app[440]: MESA-LOADER: failed to retrieve device information
Jun 05 21:02:42 raspberrypi headunit-app[440]: Unable to query physical screen size, defaulting to 100 dpi.
Jun 05 21:02:42 raspberrypi headunit-app[440]: To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
Jun 05 21:02:42 raspberrypi headunit-app[440]: JIT is disabled for QML. Property bindings and animations will be very slow. Visit https://wiki.qt.io/V4 to learn about possible solutions for your platform.
Jun 05 21:02:42 raspberrypi headunit-app[440]: Plugin Manager: Plugin loaded :  "libphone-bluetooth-plugin.so"
Jun 05 21:02:42 raspberrypi headunit-app[440]: Plugin Manager: Plugin loaded :  "libvolume-control-plugin.so"
Jun 05 21:02:42 raspberrypi headunit-app[440]: Settings Loader: ""  : Error loading settings JSON, root type should be of "items" type
Jun 05 21:02:42 raspberrypi headunit-app[440]: Loading qml plugin:  "libvolume-control-qml.so"
Jun 05 21:02:43 raspberrypi headunit-app[440]: Module 'org.viktorgino.headunit.volume' does not contain a module identifier directive - it cannot be protected from external registrations.
Jun 05 21:02:43 raspberrypi headunit-app[440]: Theme Manager: Error loading plugin :  "themes/default-theme/libdefault-theme.so" "The shared library was not found."
Jun 05 21:02:43 raspberrypi headunit-app[440]: telephony: [BluezQt] bluez manager started
Jun 05 21:02:43 raspberrypi headunit-app[440]: telephony: [BluezQt] registerAgent  :  "Manager not operational!"
Jun 05 21:02:43 raspberrypi headunit-app[440]: telephony: [BluezQt] requestDefaultAgent  :  "Manager not operational!"
Jun 05 21:02:43 raspberrypi headunit-app[440]: telephony: [BluezQt] obex service started
Jun 05 21:02:43 raspberrypi headunit-app[440]: BluezQt: InitObexManagerJob Error: "DBus session bus is not connected!"
Jun 05 21:02:43 raspberrypi headunit-app[440]: telephony: [BluezQt] obexManagerStartResult :  100 "DBus session bus is not connected!"
```

**Comment by viktorgino** [comment]
@Rootinator can you try to find the `libdefault-theme.so` file? Need to know if its missing or just located elsewhere.

**Comment by Rootinator** [comment]
The file "libdefault-theme.so" was not found.

`find: 'libdefault-theme.so': No such file or directory`

**Comment by Rootinator** [comment]
Is there anything new about this topic?

**Comment by Rootinator** [comment]
Is there anything new about this topic?

**Comment by gregd72002** [comment]
You can try using the image. Not promising it is going to resolve all your problems but the brightness should work. It is experimental though! 

https://github.com/gregd72002/headunit-desktop-rpi-imagebuilder/tree/dev/images

**Comment by Rootinator** [comment]
Thanks a lot for this!  

But I really do not want to use a completely new image because I have personalized my current system (equalizer, external soundcard as standard, ...) 

Otherwise there is no way to update the headunit without having to reconfigure everything?

**Comment by viktorgino** [comment]
@Rootinator I can build headunit and send it to you, my plan is to build have it built automatically when a new tag is added in this repo and shared to my apt repository. Will get around to do that eventually, but been tied down with navit and other stuff
