### ISSUE TITLE
Navit plugin

### ISSUE THREAD

**Issue by viktorgino** [viktorgino/headunit-desktop#38]

**Comment by viktorgino** [comment]
Navit uses a plugin system where each GUI plugin has to be registered by `plugin_register_category_gui` the QML plugin is registered and initialized here: https://github.com/navit-gps/navit/blob/trunk/navit/gui/qt5_qml/gui_qt5_qml.cpp we need to create a GUI plugin for navit that is based on this, but fits in with how the HUD plugin system works

**Comment by viktorgino** [comment]
The way navit loads the GUI on Linux, is the following:

[int main(int argc, char **argv)](https://github.com/navit-gps/navit/blob/master/navit/start.c#L22) -> [int main_real(int argc, char * const* argv)](https://github.com/navit-gps/navit/blob/master/navit/start_real.c#L74) -> ???? loads the config xml and parses it ?? -> [void navit_init(struct navit *this_)](https://github.com/navit-gps/navit/blob/master/navit/navit.c#L2061) -> [int gui_set_graphics(struct gui *this_, struct graphics *gra)](https://github.com/navit-gps/navit/blob/master/navit/gui.c#L145) -> [static int gui_qt5_qml_set_graphics(struct gui_priv* gui_priv, struct graphics* gra)](https://github.com/navit-gps/navit/blob/master/navit/gui/qt5_qml/gui_qt5_qml.cpp#L174)

**Comment by pgrandin** [comment]
I don't think that this has been tested with QT5 yet, but there was a few QT4 apps embedding navit using this method : https://wiki.navit-project.org/index.php/Embedding

**Comment by viktorgino** [comment]
Thanks @pgrandin as it seems we will have to apply some patches to navit to be able to embed it, but once the QML gui is done then it will be a lot easier than it is now. The changes that are needed currently can be seen in this commit : https://github.com/viktorgino/navit/commit/a70e4f6ff2cf3099bc2513b6630f82dbbc8b5aa4

**Comment by viktorgino** [comment]
Just to give a heads-up to anyone following: I started working on a QML based UI for navit, more details here : https://github.com/navit-gps/navit-gui-qt5/tree/master/prototypes
