### ISSUE TITLE
No voice on navigation

### ISSUE THREAD

**Issue by Rootinator** [viktorgino/headunit-desktop#39]
Hello,

Unfortunately, no voice is played on Android-Auto when navigating.
Not on Google Maps and not on Waze.

But the music gets quieter and then louder.

Is there a hidden volume control for navigation?

On the smartphone in Maps the voice is loud and active.

"Voice over Bluetooth" is disabled because the receiver does not support Bluetooth.

EDIT:
I found the mistake.

I'm using an external USB sound card and it will not play any navigation announcements. Music is played.

The navigation announcements are played via the permanently installed sound card.

How can I make the Raspberry play everything, that is music and navigation, via the external USB sound card?

**Comment by gregd72002** [comment]
Are you using RPi?

**Comment by Rootinator** [comment]
Yes

**Comment by gregd72002** [comment]
Android-auto is using alsa by default on RPi. Have you tried to change the default audio on on RPi to USB audio? Something around these lines:

    options snd-usb-audio index=0

https://raspberrypi.stackexchange.com/questions/19705/usb-card-as-my-default-audio-device
 
and disable snd_bcm2835

**Comment by Rootinator** [comment]
Music is already playing through the external USB sound card.  The built-internal, I have also disabled.  Nevertheless, no voice is played during navigation.

**Comment by Rootinator** [comment]
I would like to ask if there is already a solution, because I still have no voice output in navigation and "Ok Google" commands and hints.

The external sound card has been activated (music is playing) and the internal sound card has been deactivated.

**Comment by viktorgino** [comment]
@Rootinator no solution yet, I will have a look at this asap

**Comment by Rootinator** [comment]
Is there anything new about this topic?

**Comment by Rootinator** [comment]
Is there anything new about this topic?

**Comment by viktorgino** [comment]
@Rootinator managed to have a look at it, but i can only manage to get call audio working through Bluetooth. I'll have to have a look at different implementations to see if they managed to get it working through USB only.

**Comment by Rootinator** [comment]
That is, it will not be possible to hear the voice of the navigation (and from "Ok Google") over the Raspberry?

**Comment by viktorgino** [comment]
at the moment you'll need an external bluetooth adapter (A2DP doesn't work with the Pi's built in Bluetooth, nothing we can do about it), headunit tries to connect to the phone once AA has started, it worked for me so far.
I'm still looking into whether if there is a better solution, but I'm not sure if this is supported on stock head units or not, I don't have access to one.  But it should be doable as the voice channel is setup. Might need to send some extra config to the phone when setting up communication.
