### ISSUE TITLE
Theme Example

### ISSUE THREAD

**Issue by JohnnyKITT** [viktorgino/headunit-desktop#41]
This is related to the Theme UI switching item in Projects. i'm kinda new to Git, so i'm just dropping this here. i threw together an idea, but wanted to pitch it before i go too far down the rabbit hole. How does everyone feel about this direction for a theme?

All Colors ON
![Colored Theme](https://raw.githubusercontent.com/JohnnyKITT/headunit-desktop/6406162d7ae75c80bece631e4f763ecd1ef2519a/HeadUnitGUI-Theme.jpg)
Selected Item Colored
![Selected Item Theme](https://raw.githubusercontent.com/JohnnyKITT/headunit-desktop/6406162d7ae75c80bece631e4f763ecd1ef2519a/HeadUnitGUI-Theme-SelectedColor.jpg)
None Colored
![No Color Theme](https://raw.githubusercontent.com/JohnnyKITT/headunit-desktop/6406162d7ae75c80bece631e4f763ecd1ef2519a/HeadUnitGUI-Theme-ColorON.jpg)

**Comment by viktorgino** [comment]
I like the icons, not sure about the background and how the active element is being highlighted.
What license the icons come with?

**Comment by JohnnyKITT** [comment]
i haven't dug into the code to see how you guys wired everything, i just put together the idea in Photoshop.

All the icons, except for the Android Auto icon, are licensed under a Creative Commons Attribution 4.0 International License. You can use the icons in commercial as well as personal projects, including software, online services, templates and themes. You may modify the size, color or shape of the icons. No attribution is required. However, reselling bundles or individual pictograms is not allowed.

**Comment by JohnnyKITT** [comment]
Google also has a number of nice icons that could be used, include a Navigation one if we can't use the Android Auto icon for some reason. https://material.io/tools/icons/?style=baseline

**Comment by JohnnyKITT** [comment]
The “Android Auto app” launcher icon should only be used in the context of a UI screen, or in marketing collateral promoting or referring explicitly to the Android Auto app on mobile devices.
https://partnermarketinghub.withgoogle.com/#/brands/1fSUpZEKQJQHg77aw5ppyKX5lpFR4bOeX/1TIgcW9AH3Z7z15s9bXBHxIotiTQdFasbT29g0m7-tsQ

**Comment by viktorgino** [comment]
@JohnnyKITT Yes, this is the reason I haven't used the Android Auto icon and used the droid instead.

I have updated the backgrounds with a folder of images that can be found here : https://github.com/viktorgino/headunit-gui/tree/master/qml/theme/backgrounds but the background could be anything as it can be changed the from the gui. I think its a good idea to pick an image with darker colors and one with brighter colors and create visuals for the menu using these images instead.

I like the icons in general and its a good idea to update the menu bar with something a bit more slick looking once we find something that looks good, happy to brainstrom about possible ideas.

**Comment by JohnnyKITT** [comment]
Why didn't you want to use the AA icon? It seems to fit exactly what is allowed, "in the context of a UI screen... referring explicitly to the Android Auto app on mobile devices."

**Comment by JohnnyKITT** [comment]
They also very clearly state "DON’T. Don’t use the Android Robot." in reference to associating the robot with Android Auto.

**Comment by viktorgino** [comment]
the "Android Auto app on mobile devices" seems very ambiguous, but having read the page again its clear that they dont want to use the robot for AA, so we can go with the app logo
