### ISSUE TITLE
Missing depency

### ISSUE THREAD

**Issue by ksga** [viktorgino/headunit-desktop#44]
Hi - awesome project. Sure hope it will keep evolving :-)

In the "Install QT" section of the [instructions](http://headunit.viktorgino.me/) on there appears to be one package missing:
qtconnectivity5-dev

It results in the compile error:
> Project ERROR: Unknown module(s) in QT: bluetooth

Might save noobs like me a bit of headache when compiling :-)

**Comment by aalldridge** [comment]
At first sight, this appears to be an instance of the problem described and solved in [Issue no. 24](https://github.com/viktorgino/headunit-desktop/issues/24).
