### ISSUE TITLE
DAB+ does not work with welle.io

### ISSUE THREAD

**Issue by Rootinator** [viktorgino/headunit-desktop#48]
Hello,

I have a RTL2832U USB stick, but unfortunately "welle.io" does not find any DAB+ stations on the head unit.

However, if I connect the stick to the smartphone on which the Android app welle.io is installed, it works perfectly there.

It does not work on the head unit. The stick is detected, but there are no DAB+ stations.

How can I fix the error? 

@viktorgino 
@gregd72002

**Comment by viktorgino** [comment]
I will dedicate some time to this project this weekend, will have a look then. Welle.io needs to be updated to upstream in here

**Comment by Rootinator** [comment]
Would it then be possible that you can upload the finished image here?

http://files.headunit.viktorgino.me/index.html


(I think your head unit is very nice)

**Comment by viktorgino** [comment]
I will update the image to Raspbian Buster too. I've started working on packaging everything here, so the app can be updated via apt-get. This should make things easier. I just need to figure out how to setup a main and a nightly repo.

**Comment by Rootinator** [comment]
@viktorgino 

I have now replaced the source files of welle.io from "https://github.com/AlbrechtL/welle.io/releases/tag/v2.0-beta2 (Source Code ZIP)" to "/opt/headunit-desktop/welle.io".

Now DAB + stations are found, but I have no audio output. The squares are all green.

As an audio driver I use ALSA.

**Comment by viktorgino** [comment]
@Rootinator I've updated to the latest version of welle.io. You'll need to install some additional packages to build it : `libmp3lame-dev libsoapysdr-dev libmpg123-dev`, there are some issues with the GUI due to how the icons are being loaded to the QML context, I will have to correct those at some point, but it is usable for now. Can you try to build the latest master branch from here? It works for me on the Pi.

**Comment by Rootinator** [comment]
How can I update the head unit?

I currently use this image:
http://files.headunit.viktorgino.me/image_2018-04-15-Raspbian-viktorginos-headunit-4GB.zip

**Comment by viktorgino** [comment]
I will finish the deb build scripts and the new image in the next couple of days. Updating welle.io took way longer than I expected. Until then you'd need to manually build it, but there are some changes in dependencies etc, so I'd suggest waiting.

**Comment by Rootinator** [comment]
Thank you for your work!

**Comment by viktorgino** [comment]
@Rootinator the new image is on the way, had to first move everything to Raspbian Buster, building extra dependencies for apt now, should have something to test this evening.

**Comment by Rootinator** [comment]
That sounds great

**Comment by Rootinator** [comment]
Have you already tested the new system and is it working? 

@viktorgino

**Comment by viktorgino** [comment]
I've managed to get the updated image to build, but hud is not starting up,
I'll have some time tomorrow to debug it, but not sure what's wrong yet.
I have built the extra dependencies on buster and uploaded them to the apt
repository. My current progress is on my pi-gen repository
https://github.com/viktorgino/pi-gen

**Comment by Rootinator** [comment]
That's not great if hud does not want to start.
Would it work on a previous version of Raspbian or did you find the error why hud does not start?

**Comment by viktorgino** [comment]
I've got it working on a stock Rasbian Buster image, so now its back to debugging what's wrong with the image I generate.

**Comment by Rootinator** [comment]
I'm not sure, but you could replace the current DAB function of the HUD with welle.io or DAB-RPi (https://github.com/AlbrechtL/dab-rpi_raspbian_image) (functions + GUI), so that you can Sound over DAB would have?

Could this work?

**Comment by Rootinator** [comment]
Did you fix the error so that DAB+ can now play sound (which did not work before) and that your (new) head unit starts up again?

@viktorgino

**Comment by Rootinator** [comment]
Did you fix the error so that DAB+ can now play sound (which did not work before) and that your (new) head unit starts up again?

@viktorgino
