### ISSUE TITLE
Shutdown or close app | Restart AA after device disconnect

### ISSUE THREAD

**Issue by Vitalic66** [viktorgino/headunit-desktop#5]
First of all. THANK YOU.

I was trying for many weeks to make the headunit work on the RPI. Thank God you answered to my request at gartnera repo.

It was easy to install and ompile everything with your manual. Thumb Up for that.

My first impressions. 

You did a great job. I'm using the RPI to connect my phone via bluetooth streaming audio to my BMW. Therefor I use the Pibus. It's able to talk to the Ibus of the BMW.

Now with your program I hope I can stream video signal to the nav screen. Already did this with Kodi. But your solution is much better then Kodi or XBMC. Not only the AA option, but also Media server and DAB.

Some ideas I have:

Is there an option to close the program and get back to command line ?
Is it possible to add the media library of the phone to the media server ?
After disconnting my phone and reconnecting, nor the program or the phone was reacting. So AA stopped working.
Is it normal that "top" in console says running at 100% at your program ?

Best regards

**Comment by viktorgino** [comment]
Hi,

Thank you for checking my project out!

Having a quick read through on the [PiBUS website](http://pibus.info) it seems that you need the app to use the analogue video output, which should be as easy as setting an environment variable.
To test it run the app with the following command : `QT_QPA_EGLFS_DISPMANX_ID=1 ./headunit-app`
If its not working try : `QT_QPA_EGLFS_DISPMANX_ID=3 ./headunit-app`
To keep it just add the line to your _.profile_ file: `echo "QT_QPA_EGLFS_DISPMANX_ID=1" >> ~/.profile`
You can find [more info on this in the Qt Git repo](https://github.com/qt/qtbase/blob/5.6/src/plugins/platforms/eglfs/deviceintegration/eglfs_brcm/qeglfsbrcmintegration.cpp#L90).

ATM you can only exit the app by killing the process or pressing CTRL+C if you launched it from SSH.

The media library is still missing a lot of features, but if you can mount your phones file system, then it should be possible to scan the partitions. Other than that there isn't a way to import it without rescanning. 

There is a problem with the connection listener on the Raspberry Pi, so it doesn't detect the phones as Android devices, should work under Ubuntu tho.

I've also experienced 100% CPU usage on the Pi, even in the apps default state, without any audio or video running, I've tried profiling the GUI and got rid of smaller glitches, but something still causes it, but its not consistent as sometimes it runs fine. It is something I'm definitely looking into.

**Comment by Vitalic66** [comment]
Today i was able to install the pibus hifiberry dac board.
Sound is coming out now too.

Ctrl+c does not work. I can only ssh from another pc an kill the program.

Is it right that the phone has to be connected before the prog starts?
If i connect with already started app, AA won't work. Also dis and reconnectinh doesn't help while app was started and is running.

AA only works, if phone is connected before starting the program.

When i kill the app, and phone was not connected before, I can see error messages showing in console that the phone was recognized bit failed to open.
I will post the code soon.

Another problem is the speed at the moment. I don' t know if it is because of 100% cpu usage or the beta gl drivers. When an app is running like spotify it takes several seconds to change to another app like maps.

Also I had to recognize a problem with music. When some songs are played, the buttons and also the app doesn't react anymore. The playlist cannot be stopped. It plays and plays.... and you can go forward or anything else. Only switch to other apps.

And there is one more to fix. There is no voice coming out at google maps or when a whatsapp message is read to you. Don't know if it is because of music being played.

**Comment by viktorgino** [comment]
**Is it right that the phone has to be connected before the prog starts?**
Yes, unfortunately hotplugging doesn't work on the RPi properly, will look into that in the next couple of days. Should work on desktop tho.

**Another problem is the speed at the moment. I don' t know if it is because of 100% cpu usage or the beta gl drivers.** 
This is also something I'm working on. The app works really smooth on desktop, but really laggy on the Pi. You can use the app without the gl drivers by using the _XCB_
Qt Platform plugin and starting the app as a X session. If you want to try this, then I can write some instructions on it.

**And there is one more to fix. There is no voice coming out at google maps or when a whatsapp message is read to you. Don't know if it is because of music being played.**
Is it with the HiFiberry DAC installed? It might by because of the way the audio works. Currently it relies on ALSA, but I want to change it to use PulseAudio, that would give us better control of the audio and could implement a GUI for it as well.

**Comment by Vitalic66** [comment]
Hi,

yeah, for testing a tutorial how to set it up as desktop environment  would be nice.

Btw sound comes out when i play normal music. Maybe pulseaudio would change the error of google voice infos.

Because of the pibus, i dont have to set up anything else in the command line to get the video out to the a/v out.
The pibus board and software manages this.
