### ISSUE TITLE
Android Auto randomly crashing

### ISSUE THREAD

**Issue by SteffenAssenmacher** [viktorgino/headunit-desktop#55]
Hi, 

it keeps crashing seemingly randomly for me. Are there any log files i can view to determine the culprit?

Best regards Steffen

**Comment by viktorgino** [comment]
Hi @SteffenAssenmacher 

I've not had issues with AA crashing. Would you be able to provide some log outputs please?

**Comment by SteffenAssenmacher** [comment]
Hey @viktorgino 

Thanks for your fast response.
I would gladly share the logs but I don't really know where to find them. Where does you headunit-desktop store them?
