### ISSUE TITLE
Android Auto not connecting

### ISSUE THREAD

**Issue by girlpunk** [viktorgino/headunit-desktop#56]
Bit new to troubleshooting Android Auto stuff, but hopefully some of the info I've collected is useful. Happy to try out changes, etc. as necessary to help out.

On a freshly compiled build from `master`, connecting an Android 10 phone with Android Auto 6.0.615334-release generates the "USB device connected" message, but the Android Auto tab of headunit-desktop remains at "Please connect a device". Checking the logs shows the error `Unknown transport type`. Adding some debugging to print out the transport type shows some unprintable characters.

Changing the code around this part to force the transport to USB gets a little further, before crashing completely with the following:

    void HU::ChannelDescriptor_OutputStreamChannel_VideoConfig::set_resolution(HU::ChannelDescriptor_OutputStreamChannel_VideoConfig_VIDEO_RESOLUTION): Assertion `::HU:::ChannelDescriptor_OutputStreamChannel_VideoConfig_VIDEO_RESOLUTION_IsValid(value)` failed.

**Comment by viktorgino** [comment]
Hi @cyberjacob 

Can you please check the settings page for Android Auto? I think in the current master branch there is an issue with saving settings. I've got some changes the I'll be pushing soon so that should fix it tho.

**Comment by girlpunk** [comment]
Ah I think that's sorted it. I set the android auto settings to USB and specifying a resolution, etc. Then quit headunit from the button on the settings menu and re-opened it. After doing that the Android Auto side of things is working great.

Having a spot of trouble with some other bits, but I need to do some more digging on that. Looks like the welle.io plugin/module is having trouble with audio devices.

**Comment by viktorgino** [comment]
The welle.io plugin is running an older version of welle.io. I'm currently looking into running welle.io as its own service rather than a plugin.
