### ISSUE TITLE
can't Build the Headunit

### ISSUE THREAD

**Issue by sameershaik** [viktorgino/headunit-desktop#59]
Followed your steps for installing the per-requisites, everything went well.
When it comes to Headunit building, i am facing some issues, Below is the log
--------
sameeraaron@sameeraaron-Lenovo-Z50-70:~/hobbies/headunit-desktop$ protoc --proto_path=headunit/hu/ --cpp_out=headunit/hu/generated.x64/ headunit/hu/hu.proto
headunit/hu/: warning: directory does not exist.
headunit/hu/hu.proto: No such file or directory
sameeraaron@sameeraaron-Lenovo-Z50-70:~/hobbies/headunit-desktop$ qmake && make -j4 sub-app-pro
make: *** No rule to make target 'sub-app-pro'.  Stop.
-------

Please help me, i am new to QT

**Comment by viktorgino** [comment]
Hi @sameershaik 

Can you please try building it using the steps in the Wiki : https://github.com/viktorgino/headunit-desktop/wiki/Building-Headunit-Desktop
