### ISSUE TITLE
[Question] Android Auto client

### ISSUE THREAD

**Issue by mantielero** [viktorgino/headunit-desktop#61]
I was wondering if the Android Auto client part of the project can be used somehow as gateway between the car's factory headunit and the mobile. 

It would be nice having something like a RPi zero W with linux running some code doing something similar to what AAwireless does. 

AAwireless is a product based on [this](https://forum.xda-developers.com/t/android-4-1-proxy-gateway-for-android-auto.3813163/). The code for app is [here](https://github.com/mikeeq/aagateway).

**Comment by viktorgino** [comment]
Hi @mantielero it is entirely possible yes. The Wifi functions are not currently implemented, but its something coming sometime
