### ISSUE TITLE
[Raspberry Pi] terminate called after throwing an instance of 'int'

### ISSUE THREAD

**Issue by viktorgino** [viktorgino/headunit-desktop#7]
On Raspbian when welle.io throws an exception headunit quits with `terminate called after throwing an instance of 'int'`. Mainly thrown by https://github.com/AlbrechtL/welle.io/blob/master/src/ofdm/ofdm-processor.cpp . This behavior isn't present/haven't been observed on other platforms.

The only difference between the way welle.io loads QQmlApplicationEngine and the way headunit does is that welle.io uses dynamic allocation when creating QQmlApplicationEngine.

**Comment by Vitalic66** [comment]
Have you also seen this error popping up when starting headunit-app without dab usb stick mounted? 
Only with compiled welle.io of cause, but without the stick, app cannot be launched and you get redirected to terminal with error message just like trying to scan for dab stations.

**Comment by viktorgino** [comment]
I've seen it with both the stick attached and detached. In both cases caused by ofdm-processor. I'll change the allocation of QQmlApplicationEngine to dynamic and see what happens. The only other difference is that headunit-dekstop is compiled with STD C++11. The only thing that's strange about this is that this doesn't happen on desktop Ubuntu or Debian. 

ofdmProcessor::getSample() and ofdmProcessor::getSamples() throw the int, but that should by the try{}catch (int e) {} block in ofdmProcessor::run.
